### ISSUE TITLE
Settings don't work ?

### ISSUE THREAD

**Issue by Evileoo** [longfish801/regexpOutline#1]
First issue !

Hey, I decided to give a try to your extension, it looks like it can save me from a lot of issues

But when I edit the settings.json file, it tells me there is a problem with the setting

![image](https://github.com/longfish801/regexpOutline/assets/54958225/d56a4ba9-d3da-4095-b55e-a6979fda5293)

By default it shows the setting like this : `"regexpOutline.headerRulesEachExt": "[]"`, I got the issue when I removed the `"`

I might have not understand the readme, but it's always better to ask :)

**Comment by Evileoo** [comment]
Okay I don't know how to read

But my issue demonstrates that it would be better to edit settings in the settings.json file directly

**Comment by peekxc** [comment]
@Evileoo Can you post how you solved the issue?

**Comment by Evileoo** [comment]
I didn't solved it
Everything I tried just did not work

I closed it because it was just a misreading from me on how we are supposed to make the setting work (the subject of issue)
