### ISSUE TITLE
Settings don't work? 

### ISSUE THREAD

**Issue by peekxc** [longfish801/regexpOutline#2]
Using the example supplied in the Readme, which in my settings.json looks like: 

> "regexpOutline.headerRulesEachExt": "[{\"ext\":\".txt\",\"rules\":[{\"level\":1,\"format\":\"^■(.+)$\",\"nameIdx\":1,\"detail\":\"H1\"},{\"level\":2,\"format\":\"^□(.+)$\",\"nameIdx\":1,\"detail\":\"H2\"},{\"level\":3,\"format\":\"^▼(.+)$\",\"nameIdx\":1,\"detail\":\"H3\"}]}]"

I created a `test.txt` file with the following content: 

> ■ Header 1 
> Testing... 
> □ Sub-header 
> Another test....

And nothing shows up in the outline. How to get the extension to work? Also, It's a little strange all the strings/format inputs have to be in a compressed/line-escaped string; I don't see why this is necessary. 

It would be great if this would work, as then it would be easy to add support for the percent-format in `*.py` files, per [this issue](https://github.com/microsoft/vscode-python/issues/17218)

**Comment by longfish801** [comment]
Maybe there is a way to set up multiple lines for settings.json ...
But, I don't know how to do it !!
So Regexp Outline is designed to be set up in one line.
You can format json data to single line (minify) with web application such a [JSON整形ツール：JSON Formatter](https://one-ap-engineer.com/tools/json-formatter/) or VSCode extension [JSON Tools](https://marketplace.visualstudio.com/items?itemName=eriklynd.json-tools).

**Comment by peekxc** [comment]
Ahh even using the tool the settings do not work for me at all I'm afraid

**Comment by longfish801** [comment]
Are you still setting directly in settings.json?

The set value must be set to a *JSON string*, not *JSON*.
Directly setting in settings.json, you need to escape double quotes etc.
Here is sample.

```
    "regexpOutline.headerRulesEachExt": "[{\"ext\":\".txt\",\"rules\":[{\"level\":1,\"format\":\"^■(.+)$\",\"nameIdx\":1,\"detail\":\"H1\"},{\"level\":2,\"format\":\"^□(.+)$\",\"nameIdx\":1,\"detail\":\"H2\"},{\"level\":3,\"format\":\"^▼(.+)$\",\"nameIdx\":1,\"detail\":\"H3\"}]}]",
```

If this does not work, other extensions may be the cause.
Try disabling all other extensions and enabling only RegexpOutline.

**Comment by peekxc** [comment]
Yeah, even with copy-pasting the above into my JSON settings, nothing shows up. 

Interestingly, after changing the ".txt" to the ".py" I was able to get the regexpoutline tab to show up in the outline view. However, none of the rules seem to work

<img width="290" alt="Screenshot 2024-08-09 at 11 08 43 AM" src="https://github.com/user-attachments/assets/dbd352e6-2135-4fe6-b827-8db03e4b1422">

With either: 
<img width="373" alt="Screenshot 2024-08-09 at 11 08 49 AM" src="https://github.com/user-attachments/assets/4a89c079-73a4-4b76-b1e5-a19c41b9b7c9">

Or with: 

<img width="353" alt="Screenshot 2024-08-09 at 11 11 15 AM" src="https://github.com/user-attachments/assets/99ba55b7-317b-4a19-aa05-51bc39eac763">

Here's my rules, verbatim from the settings.json file: 

```json
"regexpOutline.headerRulesEachExt": "[{\"ext\":\".py\",\"rules\":[{\"level\":1,\"format\":\"^■(.+)$\",\"nameIdx\":1,\"detail\":\"H1\"},{\"level\":2,\"format\":\"^□(.+)$\",\"nameIdx\":1,\"detail\":\"H2\"},{\"level\":3,\"format\":\"^▼(.+)$\",\"nameIdx\":1,\"detail\":\"H3\"}]}]"
```

**Comment by longfish801** [comment]
> Interestingly, after changing the ".txt" to the ".py" I was able to get the regexpoutline tab to show up in the outline view. However, none of the rules seem to work

Then, the other extensions may be the cause.
Try disabling all other extensions, and enabling only RegexpOutline.

**Comment by longfish801** [comment]
Closed due to no progress.
