### ISSUE TITLE
TOF and EOF heading not ordered by position

### ISSUE THREAD

**Issue by L-i-o** [longfish801/regexpOutline#4]
The  heading at the beginning of the file (TOF top of file) and the heading at the end of the file (EOF end of file), are not always the first and the last headings, when the outline panel is sorted by position.
If there is a rule that matches on the first line and the heading string begins with a letter before T, the heading is placed before the TOF heading.
If there is a rule that matches on the last line and the heading string begins with a letter after E, the heading is placed after the EOF heading.
For example I use the following settings:
[{"ext":".txt","rules":[{"level":1,"format":"^([^ ].*:)$","nameIdx":1,"detail":"H1"},{"level":2,"format":"^ {0,2}([+-].*)$","nameIdx":1,"detail":"H2"},{"level":3,"format":"^ {2,}([+-].*)$","nameIdx":1,"detail":"H3"}]}]

When the Outline panel is sorted by position.
With an empty file (0 byte) I get the EOF before the TOF (wrongly ordered by name, not by position):
EOF end of file
TOF top of file

With the .txt file:
a:
z:
I get the following outline view:
a: H1
TOF top of file
EOF end of file
z: H1

Instead of:
TOF top of file
a: H1
z: H1
EOF end of file

In my opinion, when the Outline panel is sorted by position, the TOF heading should be always the first and the EOF heading should be always the last.

Can you also provide a setting to hide the TOF and EOF headings?

Thank you, for this great extension.

**Comment by longfish801** [comment]
Ah, I can't hide forever...
To tell the truth, I noticed the issue during development.
I thought it was a minor issue, so I didn't pay it any mind.
I'll think about how to handle it later.
Just a moment, please.

**Comment by longfish801** [comment]
I am thinking of making the following modifications.
If there are no objections, I will start the work this weekend (12/14).

* Establish a flag value to specify the display/non-display of TOF.
  * The flag name will be "showTOF", and the default value is true.
* Establish a flag value to specify the display/non-display of EOF.
  * The flag name will be "showEOF", and the default value is true.
* For backward compatibility, set default values for other keys as well.

The best scenario, TOF to truly display at the beginning, EOF to truly display at the end.
However, I recall that this could not be resolved during development.
Therefore, I would like to proceed with the above modifications.

**Comment by longfish801** [comment]
Just released v1.1.0.
Since it is a good opportunity, I added the bullets key.
I have been wanting to add this feature for a long time.
Then, close this issue.

* [1\.1\.0 by longfish801 · Pull Request \#5 · longfish801/regexpOutline](https://github.com/longfish801/regexpOutline/pull/5)
